//! Minimal `.bib` reader.
//!
//! Step 1 supports the subset needed by the citation preview (Steps 4–7):
//! parse `@entrytype{key, field = value, ...}` blocks into `BibEntry`s.
//! Robust parsing isn't a goal yet — most papers have well-formed `.bib`
//! files generated by reference managers.

use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::Result;
use regex::Regex;
use serde::{Deserialize, Serialize};

use crate::project::Project;
use crate::root::path_within_bounds;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BibEntry {
    pub key: String,
    pub entry_type: String,
    pub fields: HashMap<String, String>,
}

/// biblatex citation/bibliography style. Only the three most common families
/// — covers what 95% of math papers actually configure.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum BibStyle {
    /// `[1]`, `[2]`, … — biblatex `style=numeric` (default).
    #[default]
    Numeric,
    /// `[1]`, `[2]`, … sorted by author/year/title — legacy BibTeX `plain`.
    NumericSorted,
    /// `[SV06]`, `[BGL14]` — biblatex `style=alphabetic`.
    Alphabetic,
    /// `(Stroock and Varadhan, 2006)` — biblatex `style=authoryear`.
    AuthorYear,
}

/// Inspect a preamble string for a biblatex `style=…` option or a legacy
/// `\bibliographystyle{…}` directive. Falls back to `Numeric`.
pub fn detect_bib_style(preamble: &str) -> BibStyle {
    find_bib_style(preamble).unwrap_or(BibStyle::Numeric)
}

/// Inspect the root preamble and body/include files for bibliography style
/// directives. Legacy BibTeX documents usually put `\bibliographystyle{...}`
/// next to `\bibliography{...}` in the document body, so preamble-only
/// detection misses real papers.
pub fn detect_project_bib_style(project: &Project) -> BibStyle {
    if let Some(style) = find_bib_style(&project.preamble.source) {
        return style;
    }
    for file in &project.files {
        if let Some(style) = find_bib_style(&file.source) {
            return style;
        }
    }
    BibStyle::Numeric
}

fn find_bib_style(src: &str) -> Option<BibStyle> {
    let biblatex = Regex::new(r"\\usepackage\s*\[([^\]]*)\]\s*\{biblatex\}").unwrap();
    if let Some(cap) = biblatex.captures(src) {
        let opts = &cap[1];
        let key = Regex::new(r"(?:^|,)\s*style\s*=\s*([A-Za-z\-]+)").unwrap();
        if let Some(c) = key.captures(opts) {
            return Some(match c[1].to_lowercase().as_str() {
                "alphabetic" | "alphabetic-verb" => BibStyle::Alphabetic,
                "authoryear" | "authoryear-comp" | "authoryear-icomp" | "apa" => {
                    BibStyle::AuthorYear
                }
                _ => BibStyle::Numeric,
            });
        }
    }
    let bs = Regex::new(r"\\bibliographystyle\s*\{\s*([^}]+?)\s*\}").unwrap();
    if let Some(cap) = bs.captures(src) {
        let s = cap[1].to_lowercase();
        if s.contains("alpha") {
            return Some(BibStyle::Alphabetic);
        }
        if s.contains("apa") || s.contains("authoryear") {
            return Some(BibStyle::AuthorYear);
        }
        if s.contains("plain") || s.contains("abbrv") || s.contains("siam") {
            return Some(BibStyle::NumericSorted);
        }
        if s.contains("unsrt") {
            return Some(BibStyle::Numeric);
        }
        return Some(BibStyle::Numeric);
    }
    None
}

/// Build a biblatex-style alphabetic label: 1 author → first 3 letters of
/// family name; 2–4 authors → initials concatenated; 5+ → first 3 initials
/// plus `+`. All followed by the 2-digit year.
pub fn alphabetic_label(entry: &BibEntry) -> String {
    let year = entry.fields.get("year").map(|s| s.as_str()).unwrap_or("");
    let yy: String = year
        .chars()
        .rev()
        .take(2)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
        .collect();

    let authors_raw = entry
        .fields
        .get("author")
        .or_else(|| entry.fields.get("editor"))
        .map(|s| s.as_str())
        .unwrap_or("");
    let authors: Vec<&str> = authors_raw
        .split(" and ")
        .map(|s| s.trim())
        .filter(|s| !s.is_empty())
        .collect();

    let prefix = if authors.is_empty() {
        // No author — fall back to the first 3 letters of the cite key.
        entry
            .key
            .chars()
            .filter(|c| c.is_ascii_alphabetic())
            .take(3)
            .collect::<String>()
    } else if authors.len() == 1 {
        let f = family_name(authors[0]);
        f.chars()
            .filter(|c| c.is_ascii_alphabetic())
            .take(3)
            .collect::<String>()
    } else if authors.len() <= 4 {
        authors
            .iter()
            .map(|a| {
                family_name(a)
                    .chars()
                    .next()
                    .unwrap_or('X')
                    .to_ascii_uppercase()
            })
            .collect::<String>()
    } else {
        let mut s: String = authors[..3]
            .iter()
            .map(|a| {
                family_name(a)
                    .chars()
                    .next()
                    .unwrap_or('X')
                    .to_ascii_uppercase()
            })
            .collect();
        s.push('+');
        s
    };

    format!("{prefix}{yy}")
}

/// Author-year citation form: `(Stroock and Varadhan, 2006)`.
pub fn authoryear_label(entry: &BibEntry) -> String {
    let year = entry
        .fields
        .get("year")
        .map(|s| s.as_str())
        .unwrap_or("n.d.");
    let authors_raw = entry
        .fields
        .get("author")
        .or_else(|| entry.fields.get("editor"))
        .map(|s| s.as_str())
        .unwrap_or("");
    let authors: Vec<String> = authors_raw
        .split(" and ")
        .map(|a| family_name(a.trim()))
        .filter(|s| !s.is_empty())
        .collect();
    let names = match authors.len() {
        0 => "Anon.".to_string(),
        1 => authors[0].clone(),
        2 => format!("{} and {}", authors[0], authors[1]),
        _ => format!("{} et al.", authors[0]),
    };
    format!("{names}, {year}")
}

/// Extract the family (last) name from a BibTeX author entry, which may be
/// in `Last, First` or `First Last` order.
fn family_name(author: &str) -> String {
    if let Some((last, _)) = author.split_once(',') {
        last.trim().to_string()
    } else {
        author.split_whitespace().last().unwrap_or("").to_string()
    }
}

/// Sort key for alphabetic-style bibliography: (family of first author, year, title).
pub fn alphabetic_sort_key(entry: &BibEntry) -> (String, String, String) {
    let author = entry
        .fields
        .get("author")
        .or_else(|| entry.fields.get("editor"))
        .map(|s| s.as_str())
        .unwrap_or("");
    let first = author.split(" and ").next().unwrap_or("").trim();
    let year = entry.fields.get("year").cloned().unwrap_or_default();
    let title = entry.fields.get("title").cloned().unwrap_or_default();
    (family_name(first).to_lowercase(), year, title)
}

pub fn load_bib(path: &Path) -> Result<Vec<BibEntry>> {
    let src = fs::read_to_string(path)?;
    Ok(parse_bib(&src))
}

/// Locate `.bib` files referenced by the project's preamble (`\addbibresource`
/// from biblatex or `\bibliography{...}` from bibtex), load each, and return
/// a key → entry map.
pub fn load_project_bib(project: &Project) -> Result<HashMap<String, BibEntry>> {
    let mut out = HashMap::new();
    let base = project.root.parent().unwrap_or_else(|| Path::new("."));
    let mut paths = find_bib_paths(&project.preamble.source, base);
    for file in &project.files {
        paths.extend(find_bib_paths(&file.source, base));
    }

    let mut seen = HashSet::new();
    for path in paths {
        if !seen.insert(path.clone()) {
            continue;
        }
        let Ok(src) = fs::read_to_string(&path) else {
            continue;
        };
        for entry in parse_bib(&src) {
            out.entry(entry.key.clone()).or_insert(entry);
        }
    }
    Ok(out)
}

fn find_bib_paths(preamble: &str, base: &Path) -> Vec<PathBuf> {
    let addres = Regex::new(r"\\addbibresource\s*(?:\[[^\]]*\])?\s*\{\s*([^}]+?)\s*\}").unwrap();
    let bibcmd = Regex::new(r"\\bibliography\s*\{\s*([^}]+?)\s*\}").unwrap();
    let mut out = Vec::new();
    // Containment: a `.bib` path is read and its contents rendered into the
    // references section, so an untrusted document must not point it at an
    // absolute or deep-`../` file outside the project (arbitrary-file read).
    for cap in addres.captures_iter(preamble) {
        if path_within_bounds(&cap[1]) {
            out.push(resolve(&cap[1], base, "bib"));
        }
    }
    for cap in bibcmd.captures_iter(preamble) {
        // `\bibliography{a,b}` allows comma-separated names without extension.
        for name in cap[1].split(',') {
            let name = name.trim();
            if path_within_bounds(name) {
                out.push(resolve(name, base, "bib"));
            }
        }
    }
    out
}

fn resolve(name: &str, base: &Path, ext_default: &str) -> PathBuf {
    let p = Path::new(name);
    let joined = if p.is_absolute() {
        p.to_path_buf()
    } else {
        base.join(p)
    };
    if p.extension().is_some() {
        joined
    } else {
        joined.with_extension(ext_default)
    }
}

pub fn parse_bib(src: &str) -> Vec<BibEntry> {
    let head_re = Regex::new(r"@([A-Za-z]+)\s*\{\s*([^,\s]+)\s*,").unwrap();
    let bytes = src.as_bytes();
    let mut out = Vec::new();

    for m in head_re.captures_iter(src) {
        let full = m.get(0).unwrap();
        let entry_type = m.get(1).unwrap().as_str().to_lowercase();
        let key = m.get(2).unwrap().as_str().to_string();
        // Walk from after the comma, find balanced closing `}`.
        let mut i = full.end();
        let mut depth: i32 = 1;
        let content_start = i;
        while i < bytes.len() && depth > 0 {
            match bytes[i] {
                b'{' => depth += 1,
                b'}' => {
                    depth -= 1;
                    if depth == 0 {
                        break;
                    }
                }
                b'\\' if i + 1 < bytes.len() => {
                    i += 1;
                }
                _ => {}
            }
            i += 1;
        }
        let content = &src[content_start..i.min(bytes.len())];
        let _ = content_start;
        let fields = parse_fields(content);
        out.push(BibEntry {
            key,
            entry_type,
            fields,
        });
    }

    out
}

fn parse_fields(src: &str) -> HashMap<String, String> {
    let mut fields = HashMap::new();
    let bytes = src.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        // Skip whitespace and commas.
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') {
            i += 1;
        }
        if i >= bytes.len() {
            break;
        }
        // Field name.
        let name_start = i;
        while i < bytes.len()
            && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_' || bytes[i] == b'-')
        {
            i += 1;
        }
        if name_start == i {
            i += 1;
            continue;
        }
        let name = src[name_start..i].to_string();
        // = sign.
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        if i >= bytes.len() || bytes[i] != b'=' {
            break;
        }
        i += 1;
        while i < bytes.len() && bytes[i].is_ascii_whitespace() {
            i += 1;
        }
        // Value: {...}, "...", or bare token.
        let value = if i < bytes.len() && bytes[i] == b'{' {
            let mut depth = 0i32;
            let start = i + 1;
            while i < bytes.len() {
                match bytes[i] {
                    b'{' => depth += 1,
                    b'}' => {
                        depth -= 1;
                        if depth == 0 {
                            break;
                        }
                    }
                    b'\\' if i + 1 < bytes.len() => {
                        i += 1;
                    }
                    _ => {}
                }
                i += 1;
            }
            let v = src[start..i.min(bytes.len())].to_string();
            if i < bytes.len() {
                i += 1;
            }
            v
        } else if i < bytes.len() && bytes[i] == b'"' {
            let start = i + 1;
            i += 1;
            while i < bytes.len() && bytes[i] != b'"' {
                if bytes[i] == b'\\' && i + 1 < bytes.len() {
                    i += 1;
                }
                i += 1;
            }
            let v = src[start..i.min(bytes.len())].to_string();
            if i < bytes.len() {
                i += 1;
            }
            v
        } else {
            let start = i;
            while i < bytes.len() && bytes[i] != b',' && bytes[i] != b'\n' {
                i += 1;
            }
            src[start..i].trim().to_string()
        };
        fields.insert(name.to_lowercase(), value);
    }
    fields
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn one_entry() {
        let src = r#"
@article{Smith2024,
  author = {Smith, John},
  title  = {On something},
  year   = 2024,
}
"#;
        let entries = parse_bib(src);
        assert_eq!(entries.len(), 1);
        assert_eq!(entries[0].key, "Smith2024");
        assert_eq!(entries[0].entry_type, "article");
        assert_eq!(entries[0].fields.get("author").unwrap(), "Smith, John");
        assert_eq!(entries[0].fields.get("year").unwrap(), "2024");
    }

    #[test]
    fn bibliography_command_in_body_resolves_next_to_root() {
        let dir = std::env::temp_dir().join(format!("mathpreview-bib-body-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("bibo.bib"),
            r#"
@article{Smith2024,
  author = {Smith, John},
  title = {Body bibliography},
  year = {2024},
}
"#,
        )
        .unwrap();

        let root = dir.join("main.tex");
        let project = crate::project::load_project_from_source(
            &root,
            "\\begin{document}\nSee \\cite{Smith2024}.\n\\bibliography{bibo}\n\\end{document}\n"
                .to_string(),
        )
        .unwrap();
        let bib = load_project_bib(&project).unwrap();

        assert!(bib.contains_key("Smith2024"));
        assert_eq!(
            bib["Smith2024"].fields.get("title").unwrap(),
            "Body bibliography"
        );
    }

    #[test]
    fn absolute_bib_outside_project_is_not_loaded() {
        // Security: an untrusted document must not exfiltrate a file by pointing
        // `\bibliography{...}` at an absolute path outside the project.
        let secret_dir =
            std::env::temp_dir().join(format!("mathpreview-bib-secret-{}", std::process::id()));
        std::fs::create_dir_all(&secret_dir).unwrap();
        let secret = secret_dir.join("secret.bib");
        std::fs::write(
            &secret,
            "@article{Leak2024,\n  author = {X},\n  title = {SECRET},\n  year = {2024},\n}\n",
        )
        .unwrap();

        let dir = std::env::temp_dir().join(format!("mathpreview-bib-abs-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let root = dir.join("main.tex");
        let project = crate::project::load_project_from_source(
            &root,
            format!(
                "\\begin{{document}}\n\\cite{{Leak2024}}.\n\\bibliography{{{}}}\n\\end{{document}}\n",
                secret.with_extension("").display(),
            ),
        )
        .unwrap();
        let bib = load_project_bib(&project).unwrap();

        assert!(
            !bib.contains_key("Leak2024"),
            "absolute .bib path leaked entries"
        );
        let _ = std::fs::remove_dir_all(dir);
        let _ = std::fs::remove_dir_all(secret_dir);
    }
}
